# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/Git/terraces

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/Git/terraces

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Git/terraces/CMakeFiles /home/peter/Git/terraces/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Git/terraces/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named terraces

# Build rule for target.
terraces: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 terraces
.PHONY : terraces

# fast build rule for target.
terraces/fast:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/build
.PHONY : terraces/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

app/main.o: app/main.cpp.o

.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i

.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s

.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

lib/data.o: lib/data.cpp.o

.PHONY : lib/data.o

# target to build an object file
lib/data.cpp.o:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/data.cpp.o
.PHONY : lib/data.cpp.o

lib/data.i: lib/data.cpp.i

.PHONY : lib/data.i

# target to preprocess a source file
lib/data.cpp.i:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/data.cpp.i
.PHONY : lib/data.cpp.i

lib/data.s: lib/data.cpp.s

.PHONY : lib/data.s

# target to generate assembly for a file
lib/data.cpp.s:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/data.cpp.s
.PHONY : lib/data.cpp.s

lib/parse.o: lib/parse.cpp.o

.PHONY : lib/parse.o

# target to build an object file
lib/parse.cpp.o:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/parse.cpp.o
.PHONY : lib/parse.cpp.o

lib/parse.i: lib/parse.cpp.i

.PHONY : lib/parse.i

# target to preprocess a source file
lib/parse.cpp.i:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/parse.cpp.i
.PHONY : lib/parse.cpp.i

lib/parse.s: lib/parse.cpp.s

.PHONY : lib/parse.s

# target to generate assembly for a file
lib/parse.cpp.s:
	$(MAKE) -f CMakeFiles/terraces.dir/build.make CMakeFiles/terraces.dir/lib/parse.cpp.s
.PHONY : lib/parse.cpp.s

test/demo.o: test/demo.cpp.o

.PHONY : test/demo.o

# target to build an object file
test/demo.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/demo.cpp.o
.PHONY : test/demo.cpp.o

test/demo.i: test/demo.cpp.i

.PHONY : test/demo.i

# target to preprocess a source file
test/demo.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/demo.cpp.i
.PHONY : test/demo.cpp.i

test/demo.s: test/demo.cpp.s

.PHONY : test/demo.s

# target to generate assembly for a file
test/demo.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/demo.cpp.s
.PHONY : test/demo.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... terraces"
	@echo "... app"
	@echo "... unittests"
	@echo "... test"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... lib/data.o"
	@echo "... lib/data.i"
	@echo "... lib/data.s"
	@echo "... lib/parse.o"
	@echo "... lib/parse.i"
	@echo "... lib/parse.s"
	@echo "... test/demo.o"
	@echo "... test/demo.i"
	@echo "... test/demo.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

