#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser(
    description="Convert .data file to site subsets file")
parser.add_argument("input", help="The input.data file name")
parser.add_argument("output", help="The output file name")

ARGS = parser.parse_args()
SITES = []
SPECIES_COUNT = 0

with open(ARGS.input, "r") as f:
    first_line = f.readline().split(" ")
    sites_count = int(first_line[1])
    SPECIES_COUNT = int(first_line[0])
    if __debug__:
        print("Data file contains {} species with {} sites.".format(
            SPECIES_COUNT, sites_count))

    for i in range(sites_count):
        SITES.append([])

    for line in f:
        data = line.split(" ")
        data[-1] = data[-1].split("\n")[0]
        if __debug__:
            print("Encountered species with {} sites.".format(len(data)))
        for j in range(len(data) - 1):
            if data[j] == "1":
                SITES[j].append(data[-1])
            elif data[j] == "0":
                pass
            else:
                raise RuntimeError("Species {} contains illegal site existence denominator ({})".format(
                    data[-1], data[j]))

    for k in range(sites_count):
        assert len(SITES[k]) <= SPECIES_COUNT

with open(ARGS.output, "w") as f:
    species_represenation = "\n".join([" ".join(s) for s in SITES]);
    f.write(species_represenation)
