#!/bin/bash
sed -e 's/:[^),]*//g # remove branch length information
        s/)[^),]*//g # remove inner node names
		s/,/\n/g     # replace , by newline
		s/(//g       # remove opening parentheses
		s/)//g       # remove closing parentheses
		s/'"'"'//g   # remove quotes
		s/;//g       # remove semicolon at the end' $1 | sort
