#!/usr/bin/python

import sys

input_file = open(sys.argv[1], 'r');
species = []
lines = []

# read all lines
for line in input_file:
    parts = line.split();
    species.extend(parts);
    lines.append(parts);

# extract species
species = list(set(species))
species_index = range(0, len(species))
species_map = dict(zip(species, species_index))

partition_index = range(0, len(lines))

# build occurrence matrix
occ = [[0 for d in partition_index] for s in species]
i = 0
for line in lines:
    for s in line:
        occ[species_map[s]][i] = 1
    i += 1

# count occurrences per partition
partition_counts = [sum([occ[s][d] for s in species_index]) for d in partition_index]

# build reduced occurrence matrix
reduced_occ = [[] for s in species_index]
for s in species_index:
    for d in partition_index:
        if partition_counts[d] > 1:
            reduced_occ[s].append(occ[s][d])

# count occurrences per species
species_counts = [sum(reduced_occ[s]) for s in species_index]

print len(species),len(reduced_occ[0])
for s, si in species_map.items():
    assert species_counts[si] > 0
    print " ".join([str(v) for v in reduced_occ[si]]),s
